### ISSUE TITLE
Preparations search: server side

### ISSUE THREAD

**Issue by arturgummel** [geocollections/geokogud#26]
As a user, I would like to have preparations search.

Acceptance criteria:

1. REST endpoint for the client is available.
2. Search works according to the functional requirements.

**Comment by PrintScr** [comment]
Not possible to implement, since API does not provide appropriate endpoints.

**Comment by urtson** [comment]
API updated

**Comment by PrintScr** [comment]
urtson, would it possible to implement OR logical operator in API? To enable following type of queries:
SELECT * FROM Preparations WHERE LOCALITY='field_value' OR LOCALITY_EN='field_value';
Would be very useful.

There are a lot of fields in the search forms which are used to search across multiple columns in the database...
Otherwise we will need to somehow implement our workarounds such as sending multiple API requests and performing additional filtering on our side. Amount of API requests per 1 search query might be very big, depending on the number of columns this or that field is used in.

**Comment by arturgummel** [comment]
Could you please add following field in preparation?
preparation -> sample -> sample.mass

**Comment by urtson** [comment]
API updated
