### ISSUE TITLE
Drill cores search: server side

### ISSUE THREAD

**Issue by arturgummel** [geocollections/geokogud#31]
As a user, I would like to have drill cores search.

Acceptance criteria:

1. REST endpoint for the client is available.
2. Search works according to the functional requirements.

**Comment by PrintScr** [comment]
@urtson 
Hi,
It turned out that we need API to have some extra fields to fully implement this search:

1) locality__country__ISO_value

2) locality->stratigraphy.stratigraphy
locality->stratigraphy.stratigraphy_en

3) stratigraphy_free drillcore boxes:
left join drillcore_box ON drillcore.id -> drillcore_box.drillcore_id
And now required field itself: drillcore_box.stratigraphy_free

Yes, I am aware that drill core might have multiple drillcore boxes. There is no need to return stratigraphy_free from drill core boxes by default, we just want to be able to search by this field.

**Comment by urtson** [comment]
API updated
